apiVersion: v1
kind: ConfigMap
metadata:
  name: iceberg-rest-conf
  namespace: default
data:
  gravitino-iceberg-rest-server.conf: |
    gravitino.iceberg-rest.host=0.0.0.0
    gravitino.iceberg-rest.httpPort=9001
    gravitino.iceberg-rest.catalog-backend=jdbc
    gravitino.iceberg-rest.uri=jdbc:postgresql://postgres-pooler.default.svc.cluster.local:5432/iceberg_catalogue_metadata
    gravitino.iceberg-rest.warehouse=s3://e2e-mlops-data-681802563986/iceberg/warehouse/
    gravitino.iceberg-rest.io-impl=org.apache.iceberg.aws.s3.S3FileIO
    gravitino.iceberg-rest.jdbc-driver=org.postgresql.Driver
    gravitino.iceberg-rest.jdbc-max-connections=20
    gravitino.iceberg-rest.jdbc-user=app
    gravitino.iceberg-rest.jdbc-password=CnZ1LwVIvS8f8WthZK6J4ls3DCC9h6VrtewCxUQ6YPb9akoXYXZoFXymSJDNZSlV
    gravitino.iceberg-rest.jdbc-initialize=true
    gravitino.iceberg-rest.jdbc.schema-version=V1
