apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iceberg-rest-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iceberg-rest-role
subjects:
- kind: ServiceAccount
  name: iceberg-rest-sa
  namespace: default
